# The image repository to prepend to images pulled in deployments.  Such as a DockerHub proxy in Artifactory or Nexus.
# Example:
# imageRepo: "artifactory.corp.net/dockerhub-proxy/"
imageRepo: ""

harness:
  # REQUIRED: The ID of the Harness account where the agent will connect.
  # Can be obtained from the URL of your Harness account: https://app.harness.io/ng/account/<accountId>/main-dashboard
  accountId: ""

  # Optional: Identifier of the Harness Organization to install the agent into
  orgId: ""

  # Optional: Identifier of the Harness Project to install the agent into
  projectId: ""

  # URL of the Harness manager for Self Managed Platform installs.  Only needed for SMP installs.
  smpManagerURL: ""

  # PEM formatted bundle of certificates to trust on the agent. Such as self signed certs, or the CA cert and intermediate certificates used to sign internal traffic in your organization.  Needed for SMP installs or proxies doing TLS interception
  certBundle: "" #|
    # -----BEGIN CERTIFICATE-----  
    # XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    # -----END CERTIFICATE-------  
    # -----BEGIN CERTIFICATE-----  
    # XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    # -----END CERTIFICATE-------

  # Optional: List of repository server hostnames to trust, signed by the certificates listed above.  Hostnames in this list will automatically be added to the list of Repository Certificates.
  repoServers: {}
  # - server1.corp.net
  # - server2.corp.net

  agent:
    # REQUIRED: Identifier of the GitOps agent to register with Harness
    identifier: ""

    # REQUIRED: GitOps Agent Token for GitOps agent to connect to Harness control plane.
    gitOpsAgentToken: ""
